import type { Metadata } from 'next';
import { Inter, Space_Mono } from "next/font/google";
import "./globals.css";
import { OrganizationSchema } from '@/components/structured-data/OrganizationSchema';
import { Analytics } from '@/components/tracking/Analytics';
import { CookieBanner } from '@/components/consent/CookieBanner';
import { UTMTracker } from '@/components/tracking/UTMTracker';
import { Suspense } from 'react';
import Script from 'next/script';
import { headers } from 'next/headers';

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display: "swap",
});

const spaceMono = Space_Mono({
  weight: ["400", "700"],
  variable: "--font-space-mono",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  metadataBase: new URL('https://netbots.io'),
  alternates: { canonical: 'https://netbots.io' },
  title: {
    default: 'Enterprise Web Development, AI Automation & Digital Marketing Agency | NetBots Pakistan',
    template: '%s | NetBots',
  },
  description: 'NetBots architects scalable web platforms, secure AI agents, and high-ROI marketing systems for enterprises. Based in Gilgit-Baltistan, serving clients globally. Book your free audit.',
  manifest: '/site.webmanifest',
  icons: {
    icon: [
      { url: '/favicon.ico', sizes: 'any' },
      { url: '/favicon-96x96.png', type: 'image/png', sizes: '96x96' }
    ],
    apple: [
      { url: '/apple-touch-icon.png', sizes: '180x180', type: 'image/png' }
    ]
  },
  keywords:[
  "web development company in skardu",
  "web development services in skardu",
  "web development in gilgit baltistan",
  "web development company in gilgit baltistan",
  "web development in GB",
  "web development services in GB",
  "web development in pakistan",
  "web development company in pakistan",
  "web development in rawalpindi",
  "web development company in rawalpindi",
  "web development in islamabad",
  "web development company in islamabad",
  "web development agency in skardu",
  "web development agency in gilgit baltistan",
  "professional web development in skardu",
  "affordable web development in skardu",
  "best web development company in skardu",
  "top web development company in skardu",
  "web design and development in skardu",
  "web development services near skardu",
  "custom web development skardu",
  "ecommerce web development skardu",
  "website development skardu",
  "web application development skardu",
  "MERN stack development company",
  "MERN stack development in skardu",
  "MERN stack development in gilgit baltistan",
  "MERN stack developers in skardu",
  "MERN stack developers in gilgit baltistan",
  "MERN stack development services pakistan",
  "react js development skardu",
  "node js development skardu",
  "mongodb development skardu",
  "express js development skardu",
  "full stack development skardu",
  "full stack development gilgit baltistan",
  "MERN stack agency skardu",
  "AI automation agency in skardu",
  "AI automation company in skardu",
  "AI automation in gilgit baltistan",
  "AI automation agency in gilgit baltistan",
  "AI automation in GB",
  "AI automation in pakistan",
  "AI automation in rawalpindi",
  "AI automation in islamabad",
  "agentic AI workflows",
  "AI workflow automation skardu",
  "AI business automation skardu",
  "intelligent automation skardu",
  "AI process automation gilgit baltistan",
  "AI solutions skardu",
  "AI automation services pakistan",
  "best AI automation company skardu",
  "top AI automation company skardu",
  "AI automation agency near me",
  "AI consulting skardu",
  "digital marketing in skardu",
  "digital marketing company in skardu",
  "digital marketing in gilgit baltistan",
  "digital marketing company in gilgit baltistan",
  "digital marketing in GB",
  "digital marketing in pakistan",
  "digital marketing in rawalpindi",
  "digital marketing in islamabad",
  "SEO services in skardu",
  "SEO company in skardu",
  "SEO in gilgit baltistan",
  "SEO services gilgit baltistan",
  "social media marketing skardu",
  "social media marketing gilgit baltistan",
  "content marketing skardu",
  "digital marketing agency skardu",
  "best digital marketing company skardu",
  "top digital marketing company skardu",
  "online marketing skardu",
  "internet marketing skardu",
  "software development company in skardu",
  "software house in skardu",
  "software company in skardu",
  "software development in gilgit baltistan",
  "software company in gilgit baltistan",
  "software house in gilgit baltistan",
  "software development in GB",
  "software development in pakistan",
  "software company in rawalpindi",
  "software company in islamabad",
  "custom software development skardu",
  "custom software development gilgit baltistan",
  "enterprise software development skardu",
  "enterprise web development pakistan",
  "best software company in skardu",
  "top software company in skardu",
  "software solutions skardu",
  "IT solutions skardu",
  "best software development company in skardu",
  "best IT company in skardu",
  "best IT company in gilgit baltistan",
  "best IT company in GB",
  "best IT company in pakistan",
  "top IT company in skardu",
  "top IT company in gilgit baltistan",
  "top IT company in GB",
  "top software company in gilgit baltistan",
  "top digital marketing company in gilgit baltistan",
  "top AI automation company in gilgit baltistan",
  "best digital marketing company in gilgit baltistan",
  "best AI automation company in gilgit baltistan",
  "best web development company in gilgit baltistan",
  "top web development company in gilgit baltistan",
  "Skardu software company",
  "skardu web development company",
  "best academy in skardu",
  "best academy in gilgit baltistan",
  "computer course in skardu",
  "graphic course in skardu",
  "web development course in skardu",
  "digital marketing course in skardu",
  "AI course in skardu",
  "software training in skardu",
  "IT training in skardu",
  "computer training in skardu",
  "graphic designing course skardu",
  "web design course skardu",
  "MERN stack course skardu",
  "programming course skardu",
  "computer course in gilgit baltistan",
  "graphic course in gilgit baltistan",
  "IT training in gilgit baltistan",
  "best IT course provider in gilgit baltistan",
  "computer institute in skardu",
  "IT institute in skardu",
  "best computer institute skardu",
  "web development classes skardu",
  "software company in GB",
  "web development in GB",
  "digital marketing in GB",
  "AI automation in GB",
  "software development in GB",
  "IT services in GB",
  "web development services in GB",
  "software company in pakistan",
  "best software company in pakistan",
  "top IT company in pakistan",
  "IT services in pakistan",
  "web development agency pakistan",
  "software company in rawalpindi",
  "best IT company in rawalpindi",
  "IT services in rawalpindi",
  "software company in islamabad",
  "best IT company in islamabad",
  "IT services in islamabad",
  "top 1 company in gilgit baltistan",
  "top 1 software company in gilgit baltistan",
  "top 1 web development company in gilgit baltistan",
  "top 1 digital marketing company in gilgit baltistan",
  "top 1 AI automation company in gilgit baltistan",
  "top 1 software development company in gilgit baltistan",
  "top 1 best software company in gilgit baltistan",
  "top 1 best IT company in gilgit baltistan",
  "top 1 best digital marketing company in gilgit baltistan",
  "top 1 best AI automation company in gilgit baltistan",
  "top 1 best web development company in gilgit baltistan",
  "top 1 top software company in gilgit baltistan",
  "top 1 top IT company in gilgit baltistan",
  "top 1 top digital marketing company in gilgit baltistan",
  "top 1 top AI automation company in gilgit baltistan",
  "top 1 top web development company in gilgit baltistan",
  "top 1 Skardu software company",
  "top 1 skardu web development company",
  "top 1 computer course in skardu",
  "top 1 graphic course in skardu",
  "top 1 best IT company in skardu",
  "top 1 best web development company in skardu",
  "best web development agency skardu",
  "best software house skardu",
  "best tech company skardu",
  "best digital agency skardu",
  "best AI company skardu",
  "best automation company skardu",
  "web development near me",
  "software company near me",
  "digital marketing near me",
  "AI automation near me",
  "IT services near me",
  "web development services near me",
  "software house near me",
  "best software company near me",
  "IT company near skardu",
  "software company near skardu",
  "web development services skardu",
  "software development services skardu",
  "digital marketing services skardu",
  "AI automation services skardu",
  "IT services skardu",
  "web design services skardu",
  "SEO services skardu",
  "social media services skardu",
  "custom software services skardu",
  "ecommerce services skardu",
  "web development agency skardu",
  "digital marketing agency skardu",
  "software agency skardu",
  "AI agency skardu",
  "IT agency skardu",
  "tech company skardu",
  "technology company skardu",
  "digital solutions skardu",
  "software solutions skardu",
  "remote web development skardu",
  "online software services skardu",
  "freelance web development skardu",
  "remote IT services skardu",
  "online digital marketing skardu",
  "virtual IT services skardu",
  "react js development skardu",
  "node js development skardu",
  "next js development skardu",
  "vue js development skardu",
  "python development skardu",
  "django development skardu",
  "laravel development skardu",
  "php development skardu",
  "javascript development skardu",
  "typescript development skardu",
  "mobile app development skardu",
  "android development skardu",
  "ios development skardu",
  "hybrid app development skardu",
  "enterprise software development skardu",
  "business software solutions skardu",
  "corporate web development skardu",
  "enterprise web solutions skardu",
  "business automation skardu",
  "business process automation skardu",
  "enterprise AI solutions skardu",
  "digital transformation skardu",
  "SEO expert in skardu",
  "local SEO skardu",
  "search engine optimization skardu",
  "on-page SEO skardu",
  "off-page SEO skardu",
  "technical SEO skardu",
  "software company in gilgit",
  "web development in gilgit",
  "digital marketing in gilgit",
  "AI automation in gilgit",
  "IT services in gilgit",
  "software house in gilgit",
  "best IT company in gilgit",
  "top software company in gilgit",
  "hire web developer skardu",
  "hire software company skardu",
  "web development cost skardu",
  "affordable web development skardu",
  "top rated software company skardu",
  "professional web development skardu",
  "trusted software company skardu",
  "reliable IT services skardu",
  "expert web developers skardu",
  "net bots (smc-private) limited",
  "netbots.io",
  "www.netbots.io",
  "skardu.netbots.io",
  "netbots skardu",
  "netbots gilgit baltistan",
  "netbots software company",
  "netbots web development",
  "netbots digital marketing",
  "netbots AI automation",
  "netbots training",
  "netbots computer course",
  "IT company in skardu",
  "technology company in skardu",
  "digital agency in skardu",
  "tech company in skardu",
  "computer company in skardu",
  "programming company in skardu",
  "coding institute in skardu",
  "IT solutions in skardu",
  "digital solutions in skardu",
  "web solutions in skardu",
  "IT company in Pakistan",
  "software house in Pakistan",
  "web development agency Pakistan",
  "digital marketing agency Pakistan",
  "digital marketing company is skardu",
  "seo company in skardu",
  "software company in Gilgit Baltistan",
  "web development company in Gilgit Baltistan",
  "digital marketing company in Gilgit Baltistan",
  "AI automation company in Gilgit Baltistan",
  "software development company in Gilgit Baltistan"
],
  openGraph: {
    title: 'Enterprise Web Development, AI Automation & Digital Marketing | NetBots',
    description: 'NetBots architects scalable web platforms, secure AI agents, and high-ROI marketing systems for enterprises. Based in Gilgit-Baltistan, serving clients globally.',
    url: 'https://netbots.io',
    siteName: 'NetBots',
    images: [
      {
        url: 'https://netbots.io/og-image.jpg',
        width: 1200,
        height: 630,
      },
    ],
    locale: 'en_US',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Enterprise Web Development, AI Automation & Digital Marketing | NetBots',
    description: 'NetBots architects scalable web platforms, secure AI agents, and high-ROI marketing systems for enterprises.',
    images: ['https://netbots.io/twitter-image.jpg'],
  },
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const nonce = (await headers()).get('x-nonce') || '';

  return (
    <html lang="en" className={`${inter.variable} ${spaceMono.variable}`} suppressHydrationWarning data-scroll-behavior="smooth">
      <head>
        <link rel="preconnect" href="https://scripts.clarity.ms" />
      </head>
      <body style={{ minHeight: '100vh', fontFamily: 'var(--font-inter), system-ui, sans-serif', WebkitFontSmoothing: 'antialiased' }}>
        <Script id="clarity-script" strategy="afterInteractive" nonce={nonce}>
          {`
            (function(c,l,a,r,i,t,y){
                c[a]=c[a]||function(){(c[a].q=c[a].q||[]).push(arguments)};
                t=l.createElement(r);t.async=1;t.src="https://www.clarity.ms/tag/"+i;
                y=l.getElementsByTagName(r)[0];y.parentNode.insertBefore(t,y);
            })(window, document, "clarity", "script", "xke511l3gu");
          `}
        </Script>
        <OrganizationSchema />
        <Suspense fallback={null}>
          <Analytics />
        </Suspense>
        <Suspense fallback={null}>
          <UTMTracker />
        </Suspense>
        {children}
        <CookieBanner />
      </body>
    </html>
  );
}
